### ISSUE TITLE
Make bot look like it is typing while processing a request

### ISSUE THREAD

**Issue by ScottJDaley** [ScottJDaley/ada#68]
```
async with message.channel.typing():
  ...
```

From here: https://github.com/SpectrixOfficial/discordpy-dialogflow-chatbot/blob/master/rewrite/chatbot-rewrite.py

**Comment by lakshyashastri** [comment]
Do you still need help on this one @ScottJDaley

**Comment by ScottJDaley** [comment]
Hi @LakshyaShastri! Unfortunately, I stopped working on this project several months ago. You are welcome to fork this repo and add the feature yourself. Or you can send a PR and I can try to take a look in the next week or so.

**Comment by ScottJDaley** [comment]
Does this automatically with slash commands
