### ISSUE TITLE
Error: In embed.fields.2.value Must be 1024 or fewer in length - caused by: Producing query Turbo motors

### ISSUE THREAD

**Issue by Kirihan** [ScottJDaley/ada#76]
Hello, i did the following command:

ada produce 1 turbo motor

and it produces no result, as I'm self-hosting I see the following log:

0|bot  | Ignoring exception in on_message
0|bot  | Traceback (most recent call last):
0|bot  |   File "/home/kirihan/.local/lib/python3.6/site-packages/discord/client.py", line 333, in _run_event
0|bot  |     await coro(*args, **kwargs)
0|bot  |   File "/home/kirihan/shared/ada/bot.py", line 57, in on_message
0|bot  |     file=result_message.file)
0|bot  |   File "/home/kirihan/.local/lib/python3.6/site-packages/discord/abc.py", line 887, in send
0|bot  |     content=content, tts=tts, embed=embed, nonce=nonce)
0|bot  |   File "/home/kirihan/.local/lib/python3.6/site-packages/discord/http.py", line 245, in request
0|bot  |     raise HTTPException(r, data)
0|bot  | discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
0|bot  | In embed.fields.2.value: Must be 1024 or fewer in length.

It seems to have hit the limit of characters in the field of embed

**Comment by ScottJDaley** [comment]
I believe this is fixed in https://github.com/ScottJDaley/ada/commit/13c3cc390bb4423819d62557b579f73a9d2a0d06
